cryostatio/cryostat-core

- .gitignore
- pom.xml
- src/main/java/com/redhat/rhjmc/containerjfr/core/FlightRecorderException.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/net/JFRConnection.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/templates/RemoteTemplateService.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/templates/Template.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/templates/TemplateService.java
- src/main/java/org/openjdk/jmc/ui/UIPlugin.java
- src/test/java/com/redhat/rhjmc/containerjfr/core/templates/RemoteTemplateServiceTest.java
- src/test/resources/com/redhat/rhjmc/containerjfr/core/templates/profile.jfc
Related to rh-jmc-team/container-jfr#141
Related to rh-jmc-team/container-jfr#142
These changes support rh-jmc-team/container-jfr#140 , which adds a command to list template names on the remote VM and enables an event string syntax to select these templates.
> Implement TemplateService for target VM event templates

- pom.xml
This sets the targeted upstream JMC version to 7.1.1, the latest in the 7 release series, rather than a rolling 8 development snapshot.
The JMC `jdp` artifactId has been put back to where it is located in JMC7. It had previously been updated for the changed location that will be present in JMC8.
> Target JMC 7.1.1

- pom.xml
- src/main/java/com/redhat/rhjmc/containerjfr/core/net/JFRConnection.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/net/JFRConnectionToolkit.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/sys/FileSystem.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/templates/AbstractTemplateService.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/templates/LocalStorageTemplateService.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/templates/MalformedXMLException.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/templates/MergedTemplateService.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/templates/MutableTemplateService.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/templates/RemoteTemplateService.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/templates/Template.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/templates/TemplateService.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/templates/TemplateType.java
- src/main/java/org/openjdk/jmc/flightrecorder/controlpanel/ui/ControlPanel.java
- src/main/java/org/openjdk/jmc/ui/MCAbstractUIPlugin.java
- src/main/java/org/openjdk/jmc/ui/UIPlugin.java
- src/test/java/com/redhat/rhjmc/containerjfr/core/net/JFRConnectionToolkitTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/core/templates/LocalStorageTemplateServiceTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/core/templates/RemoteTemplateServiceTest.java
See also: rh-jmc-team/container-jfr#199
This PR extends the Templates API to allow the raw template XMLs to be retrieved, and to allow custom template XMLs to be added, parsed, validated, and saved to the local filesystem. These custom templates can be retrieved on their own, or in a "merged" view alongside the built-in templates for a specific remote target.
> Local, Mutable Templates

- src/main/java/com/redhat/rhjmc/containerjfr/core/EventOptionsCustomizer.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/net/Credentials.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/net/JFRConnection.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/net/JFRConnectionToolkit.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/templates/AbstractTemplateService.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/templates/MergedTemplateService.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/templates/RemoteTemplateService.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/templates/TemplateService.java
- src/test/java/com/redhat/rhjmc/containerjfr/core/EventOptionsCustomizerTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/core/net/JFRConnectionToolkitTest.java
Related to rh-jmc-team/container-jfr#5
This causes JFRConnections to lazy-initialize, waiting until the consumer attempts to retrieve a Flight Recorder Service handle or other connection-required resource. When a connection attempt is made, optional JMX authentication credentials can be supplied to authenticate the request against the target's remote JMX access control. If these credentials are not supplied or are invalid, the connection attempt fails with an identifiable exception, allowing API consumers to implement ex. a mechanism for requesting credentials from the user, or at least notifying the user of the specific reason for the connection attempt failure.
> Initial JMX authentication foundation

- pom.xml
- src/main/java/com/redhat/rhjmc/containerjfr/core/net/Credentials.java
This allows Credentials and types which contain them (specifically, ContainerJFR's ConnectionDescriptor) to be used in Collection types like HashMaps. This is useful because a ConnectionDescriptor is a fairly natural caching key.
> Credentials implements equals/hashCode

- src/main/java/com/redhat/rhjmc/containerjfr/core/net/JFRConnectionToolkit.java
- src/test/java/com/redhat/rhjmc/containerjfr/core/net/JFRConnectionToolkitTest.java
Fixes #44.
These are the methods I didn't add. Would any of them be helpful to have?
```
public static ObjectName createObjectName(String name)
public static MemoryMXBean getMemoryBean(MBeanServerConnection server)
public static RuntimeMXBean getRuntimeBean(MBeanServerConnection server)
public static ThreadMXBean getThreadBean(MBeanServerConnection server)
public static OperatingSystemMXBean getOperatingSystemBean(MBeanServerConnection server)
public static Object invokeOperation(MBeanServerConnection server, ObjectName on, String operation, Object ... parameters)
public static boolean isJavaVersionAboveOrEqual(IConnectionHandle connectionHandle, JavaVersion minVersion)
> Add Functions from JMC's ConnectionToolkit

- src/main/java/com/redhat/rhjmc/containerjfr/core/net/Credentials.java
Mark credentials fields as transient to ensure serialization tools do not serialize the contents of Credentials objects.
https://sites.google.com/site/gson/gson-user-guide#TOC-Finer-Points-with-Objects
> Avoid serializing credentials

- pom.xml
- src/main/java/com/redhat/rhjmc/containerjfr/core/net/discovery/JvmDiscoveryClient.java
Related to rh-jmc-team/container-jfr#158
This adds a thin wrapper around the existing JMC JDP async discovery listener mechanism, exposing it so ContainerJFR can listen asynchronously for changes to the set of known targets. These changes can then be written as Notifications (rh-jmc-team/container-jfr#330) and responded to by remote clients asynchronously, without client-side polling.
> Add thin async JDP wrapper

- pom.xml
We shouldn't need this included as a runtime dependency.
> Use provided scope for spotbugs-annotation

- README.md
- pom.xml
Removes need to manually build JMC locally into .m2 repository
Now that the non-core JMC pieces we use in -core have been copied into our tree, even if temporarily, we can avoid the requirement of manually building JMC at all by adding the AdoptOpenJDK repo for JMC Core to our -core's pom. Eventually the JMC Core dependencies should end up on Maven Central as well, so this repository definition can be removed.
> Add AdoptOpenJDK Maven repo

- pom.xml
The version was previously set to `2.3.0-SNAPSHOT`, however the last tag was on `2.2.2`. This "bumps" it to `2.2.3` and will be the first tagged version after the Cryostat rename. The plan is to start using `SNAPSHOT` versions for development, however for simplicity's sake it will be easier to finish the rename of the Crysotat main project with a `2.2.3` tagged version here first.
> Bump version to 2.2.3

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
- .github/workflows/semantic-pr.yml
- .mergify.yml
Apply configurations from cryostatio/cryostat#550, cryostatio/cryostat#549, cryostatio/cryostat#553
> ci(config): apply CI actions configs

- src/main/java/io/cryostat/core/reports/InterruptibleReportGenerator.java
Fixes #117
Question: How do I test this change with my other branch in `~/cryostat`? I tried the below commands on my `record-rule-event` branches, started smoketest, started a new recording on `service:jmx:rmi:///jndi/rmi://cryostat:10000/jmxrmi` with the updated Cryostat template, generated a report, then downloaded the recording. I couldn't find any instances of my custom event in the recording file with `jfr print <recording_name>.jfr | vim -`. What am I missing?
```
~/cryostat-core $ mvn install
~/cryostat-core $ cd ~/cryostat
~/cryostat $ mvn clean package && CRYOSTAT_DISABLE_SSL=true CRYOSTAT_DISABLE_JMX_AUTH=true sh smoketest.sh
```
> feat(reports): Add JFR event for report rules

- pom.xml
Related https://github.com/cryostatio/cryostat/issues/566
> Oh, we'll also need a -core minor version release cut and the pom.xml here updated to point to that new version.
_Originally posted by @andrewazores in https://github.com/cryostatio/cryostat/issues/855#issuecomment-1064473901_
> build(version): set version to 2.9.0

- src/main/java/io/cryostat/core/templates/LocalStorageTemplateService.java
- src/test/java/io/cryostat/core/templates/LocalStorageTemplateServiceTest.java
- src/test/resources/io/cryostat/core/templates/multiword_label.jfc
Related to cryostatio/cryostat#890
This is really the entire fix for the above issue, but I will have to create a new upstream tag version and point Cryostat's `pom.xml` at that version and then merge that PR to really close the issue.
If an event template document is added where the root element's `label` attribute contains non-word characters (`[\\W]` ie `[a-zA-Z_0-9]`), then replace those characters with `_`.
> fix(template): sanitize custom template names on add

- pom.xml
#132 bugfix PR has been merged and backported, so this PR bumps the version to prep for tagging as 2.9.1 to use in the main Cryostat 2.1 release branch.
> chore(pom): set version to 2.9.1

- pom.xml
Currently in `main` the `pom` version is still 2.9.0, which matches the latest git tag but also matches the `cryostat-v2.1` branch. This sets it to `2.10.0-SNAPSHOT` for the start of the next development iteration.
> chore(pom): set version to 2.10.0-SNAPSHOT

- src/main/java/io/cryostat/core/reports/InterruptibleReportGenerator.java
- src/test/java/io/cryostat/core/reports/InterruptibleReportGeneratorTest.java
Related to #136
Not sure if this is all we need to allow callers to specify rules because all it is, is a method overload with an extra parameter added. Feedback is appreciated.
I was thinking maybe if the Collection of rules is empty or null that there would be some custom exception that would need to be implemented? But I am also confused as to how to test cryostat-core implementations in general.
> feat(reports): report generator allows callers to specify which rules to evaluate

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- .mvn/jvm.config
- README.md
- pom.xml
- src/main/java/io/cryostat/core/agent/LocalProbeTemplateService.java
- src/main/java/io/cryostat/core/sys/Clock.java
- src/main/java/io/cryostat/core/templates/LocalStorageTemplateService.java
- src/test/java/io/cryostat/core/EventOptionsCustomizerTest.java
- src/test/java/io/cryostat/core/RecordingOptionsCustomizerTest.java
- src/test/java/io/cryostat/core/reports/ReportGeneratorTest.java
- src/test/java/io/cryostat/core/templates/LocalStorageTemplateServiceTest.java
- src/test/java/io/cryostat/core/templates/RemoteTemplateServiceTest.java
Fixes #137
The `.mvn/jvm.config` file is needed for now as a workaround on https://github.com/diffplug/spotless/issues/834 . One Mockito static method has been removed so it was replaced with an equivalent. Everything else is pretty routine.
> chore(pom): update to JDK17

- pom.xml
- src/main/java/io/cryostat/core/net/JFRConnection.java
Related https://github.com/cryostatio/cryostat/issues/960
Related https://github.com/cryostatio/cryostat-web/issues/442
~~Adds a getter that returns the JFRConnection server descriptor's GUID.~~
Adds a getter that computes a hashcode based on jvm runtime properties.
> feat(jmx): compute unique jvm id

- .github/workflows/ci.yaml
- README.md
- pom.xml
The cryostat-agent has some use cases for -core, such as being able to compute its own JVM ID. The agent targets JDK 11 for wider compatibility, so -core should target 11 as well as the lowest common denominator.
> chore(build): target JDK 11

- .github/workflows/maven-publish.yaml
- README.md
Related to #92
Config is directly copied from the `-agent` repo where it's already set up and seems to be working (my `quarkus-test` consumes that). Machines where builds consuming this artifact will be run will need a Maven configuration as follows:
https://github.com/andrewazores/quarkus-test#packaging-and-running-the-application
Since this is on release only, there would be no `-SNAPSHOT` builds available for consumers. Not sure if we want to bother with that now and build/publish a `-SNAPSHOT` every time there is a merge to `main`. I think that can probably wait until later on if we decide this works well enough.
> build(github): publish JAR to GH pkgs on release

- .github/workflows/ci.yaml
Related to https://github.com/cryostatio/cryostat/issues/1401
See https://github.com/actions/setup-java#supported-distributions
Update ci to use `temurin` jdk.
> chore(ci): use temurin distribution jdk

- .mergify.yml
Related to https://github.com/cryostatio/cryostat/issues/1459
Missing mergify update for release branching.
> ci(mergify): update config for 2.3 release branch

- src/main/java/io/cryostat/core/net/JFRJMXConnection.java
> fix(jmx): enable connection to GraalVM native images

- src/main/java/io/cryostat/core/agent/LocalProbeTemplateService.java
- src/main/java/io/cryostat/core/agent/ProbeTemplate.java
Fixes #239 
Changes include:
- `addTemplate` should check if template file exists before validating.
- Add more contexts in case file-exist error occurs.
- ProbeTemplate should correctly set its name.
- `addTemplate` should return the `ProbeTemplate` object so that the caller can directly call `serialize` on it.
- Input streams should properly close using the custom `trulyClose`.
- Rename methods to match returned values.
> chore(jmc-agent): clean up probe template utility

- src/main/java/io/cryostat/core/agent/CapturedValue.java
Fixes #238
Was converting these tag text contents into uppercase because of the corresponding enum was uppercase and the validation does not like that. I added a toString override to fix this.
> chore(jmc-agent): fix probe-template event>method>paramter>contenttypes serialization

- src/main/java/io/cryostat/core/EventOptionsBuilder.java
- src/main/java/io/cryostat/core/net/CryostatFlightRecorderService.java
- src/main/java/io/cryostat/core/net/JFRJMXConnection.java
- src/main/java/io/cryostat/core/net/JmxFlightRecorderService.java
- src/main/java/io/cryostat/core/serialization/SerializableEventTypeInfo.java
- src/main/java/io/cryostat/core/serialization/SerializableOptionDescriptor.java
- src/main/java/io/cryostat/core/serialization/SerializableRecordingDescriptor.java
- src/main/java/io/cryostat/core/templates/RemoteTemplateService.java
- src/test/java/io/cryostat/core/EventOptionsCustomizerTest.java
- src/test/java/io/cryostat/core/templates/RemoteTemplateServiceTest.java
- chore(svc): extract EventOptionsBuilder from Cryostat application
- chore(svc): add recording start method using event template name and type
Related to https://github.com/cryostatio/cryostat-agent/issues/162
Related to https://github.com/cryostatio/cryostat/issues/1578
This extracts the `EventOptionsBuilder` from the Cryostat application into `-core`, then augments the JMC `IFlightRecorderService` by introducing a subinterface `CryostatFlightRecorderService` that allows for additional/higher-level operations, such as dynamically starting a recording using an event template name+type rather than the JMC `IConstrainedMap`. This will support starting recordings by network request by asking the Agent to simply use a `.jfc` file available to it locally, rather than needing to reserialize …
> feat(svc): add recording start method using event template name and type

- .github/workflows/push-ci.yml
> chore(ci): restore CI on push workflow

- .github/workflows/ci.yaml
- .github/workflows/cryostat-test.yml
> feat(ci): add status check for new workflow

- src/main/java/io/cryostat/core/JvmIdentifier.java
- src/main/java/io/cryostat/core/net/JFRConnection.java
- src/main/java/io/cryostat/core/net/JFRJMXConnection.java
- src/main/java/io/cryostat/core/net/RuntimeMetrics.java
Related to https://github.com/cryostatio/cryostat-agent/issues/278
> feat(jvmid): provide method for determining JVM's own hash ID without JMX connection

- .github/workflows/ci.yml
- .github/workflows/cryostat-test.yml
> chore(ci): Fix bug when caching maven files for Cryostat build

- .github/workflows/ci.yml
- .github/workflows/cryostat-test.yml
fixes: #315
Basically, when caching the maven files, the key that we use is unique to each version of the `pom.xml` file. When we checkout the `Cryostat` repo, which has a different `pom.xml` file, we are unable to hit the exact key that we saved the cache under because the hashes of the two different `pom.xml` files are different. Additionally, we are not hitting the cache that was most recently produced for some reason. Therefore, sometimes with changes like the update to `2.26.0-SNAPSHOT`, we are actually restoring an older version of -core that hasn't been updated yet.
Here, the change I've made just checks out the -core PR branch before checking out the main `Cryostat` branch so the right files are cached into the `~/.m2` folder.
> chore(ci): checkout core first to cache

- src/main/java/io/cryostat/core/serialization/SerializableRecordingDescriptor.java
> fix(serialization): recording serialization properly converts recording state types

- src/main/java/io/cryostat/core/reports/InterruptibleReportGenerator.java
Related to https://github.com/cryostatio/cryostat3/pull/104
> chore(rules): touchups for Jackson serialization

- .github/workflows/ci.yml
> feat(ci): should build cryostat3 as well as cryostat (2.x)

- .github/workflows/maven-central-release.yml
- pom.xml
- release.sh
See https://github.com/RedHatInsights/insights-java-agent/pull/12
Fixes #92
> ci(central): add configurations for JReleaser publication to Maven Central

- .github/workflows/maven-central-release.yml
- .github/workflows/maven-publish.yml
Related to #92
Related to #338
Removes the version updating automation from the workflow since this is not working with the branch protection rules we have set for `main` and the `github-actions[bot]` pseudo-user, nor the PAT that we use for other similar updates with web-client submodules.
For now this is left as a manual step that publishes the current (probably `-SNAPSHOT`) version from `main` directly to central. Once that's working I'll follow up with another PR to merge that workflow into the [pre-existing one](https://github.com/cryostatio/cryostat-core/blob/main/.github/workflows/maven-publish.yml) that builds and publishes to the GitHub Maven Packages repository, so that this new action for publishing to Maven Central is just an automatic addition to our existing release workflow …
> ci(central): remove workflow version update automation

- pom.xml
Our group ID is set up to publish to the newer s01 host: https://central.sonatype.org/publish/publish-maven/#deployment
Related to: #92
> chore(maven): change URL for Maven Central publishing

- README.md
- pom.xml
> docs(readme): remove GitHub Packages Maven config note

- .github/workflows/ci.yml
> fix(CI): checkout -core to cache mvn files before building Cryostat3

- src/main/java/io/cryostat/core/net/discovery/JvmDiscoveryClient.java
- src/main/java/io/cryostat/core/reports/InterruptibleReportGenerator.java
- src/test/java/io/cryostat/core/net/discovery/JvmDiscoveryClientTest.java
- src/test/java/io/cryostat/core/reports/InterruptibleReportGeneratorTest.java
Related to #348
No need to pass in logger instances anymore, they can and should just use the LoggerFactory to get an instance for themselves.
> chore(logger): do not pass logger instances into constructors

- src/main/java/io/cryostat/core/reports/InterruptibleReportGenerator.java
`RuleEvaluator` causes the whole queue of futures to be evaluated by whoever calls `evaluator.run()` - in this case, one thread from the Executor. If there are many threads available via that Executor then we don't take any advantage of the parallelism possible in analysis rules this way. With this PR this `RuleEvaluator` is removed and each rule in the queue to be processed is immediately submitted to the executor pool, then the final results are all collected by the `qThread` and returned. This way a multithreaded executor provides more parallelism within individual rule analyses, rather than only helping to parallelize multiple analyses - ie parallelism within a single file analysis instead of only at the per-file level.
> fix(reports): split rule evaluations across executor submissions

- pom.xml
Fixes #355
Useful for Quarkus in Cryostat 3.
> chore(build): include jandex plugin

- src/main/java/io/cryostat/core/net/MemoryMetrics.java
- src/main/java/io/cryostat/core/net/MemoryUtilization.java
Fixes #356
Depends on #357
Workaround related to https://github.com/cryostatio/cryostat3/pull/307 . Quarkus fails to index `java.lang.management.MemoryUsage` and this causes the GraphQL schema validation to fail, since the type is found in the generated schema but is not indexed. Creating this type separately and indexing it with #357 works and is a less leaky abstraction.
> chore(mbeans): use own-defined type to replace java.lang.management.MemoryUsage

- src/main/java/io/cryostat/core/net/MBeanMetrics.java
- src/main/java/io/cryostat/core/net/MemoryMetrics.java
- src/main/java/io/cryostat/core/net/MemoryUtilization.java
- src/main/java/io/cryostat/core/net/OperatingSystemMetrics.java
- src/main/java/io/cryostat/core/net/RuntimeMetrics.java
- src/main/java/io/cryostat/core/net/ThreadMetrics.java
- src/main/java/io/cryostat/core/serialization/SerializableEventTypeInfo.java
- src/main/java/io/cryostat/core/serialization/SerializableOptionDescriptor.java
- src/main/java/io/cryostat/core/serialization/SerializableRecordingDescriptor.java
Related to https://github.com/cryostatio/cryostat3/pull/342
> fix(serialization): no-args constructors and non-final fields for Jackson

- src/main/java/io/cryostat/core/agent/Event.java
Followup PR to go alongside https://github.com/cryostatio/cryostat3/pull/375
This makes the fields in the Event class visible, allowing them to be serialized for the API/Web UI. 
Related to https://github.com/cryostatio/cryostat3/issues/14
> chore(jmcagent): correct Event field visibility

- src/main/java/io/cryostat/core/agent/AgentJMXHelper.java
Related to https://github.com/cryostatio/cryostat3/issues/14
This PR makes the ProbeValidationException and MBeanRetrieveException visible so they can be caught explicitly by consumers (e.g. the Probe handlers in cryostat main).
> fix(jmcagent): widen exception subclass visiblity

- .github/workflows/push-ci.yml
Can't call a reusable workflow from a step. Added `runs-on` property.
Related to: #392
> ci(maven): fix snapshot publishing job

- .github/workflows/push-ci.yml
> ci(maven): run checkout before querying project version

- pom.xml
Reverts cryostatio/cryostat-core#399
Looks like this causes a build failure:
https://github.com/cryostatio/cryostat3/actions/runs/9129557915/job/25104421866
```
Error:    Run 3: HealthTest.testHealthLiveness » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
Error: ]: Build step io.quarkus.deployment.index.ApplicationArchiveBuildStep#build threw an exception: org.jboss.jandex.UnsupportedVersion: Can't read Jandex index from /META-INF/jandex.idx: Can't read index version 12; this IndexReader only supports index versions 2-3,6-11
at io.quarkus.deployment.index.IndexingUtil$MetaInfJandexReader.apply(IndexingUtil.java:288)
at io.quarkus.deployment.index.IndexingUtil$MetaInfJandexReader.apply(IndexingUtil.java:264)
at …
```
> build(deps): revert io.smallrye:jandex-maven-plugin from 3.2.0 to 3.1.8

- src/main/java/io/cryostat/core/templates/RemoteTemplateService.java
- src/main/java/io/cryostat/core/templates/TemplateService.java
- src/test/java/io/cryostat/core/templates/RemoteTemplateServiceTest.java
This PR cleans up the template service to avoid exposing the document type, changing getXML to return the XML string directly as it's used in the S3 template service/api handlers.
Fixes https://github.com/cryostatio/cryostat-core/issues/300
> chore(cleanup): Abstract away document type

- src/main/java/io/cryostat/core/net/CryostatFlightRecorderService.java
- src/main/java/io/cryostat/core/net/JmxFlightRecorderService.java
Related to https://github.com/cryostatio/cryostat3/issues/491
Related to #389
> chore(jsoup): remove useless Document type from method signature

- .github/workflows/ci.yml
Since renaming the original Cryostat repo to `cryostat-legacy` and Cryostat3 back onto `cryostat`, the CI here has been broken. Here's a failed run: https://github.com/cryostatio/cryostat-core/actions/runs/9542552901/job/26297574264?pr=406
> ci(cryostat): update repo and tags for renaming

- .github/workflows/ci.yml
- cryostat-core/pom.xml
- cryostat-core/src/main/java/io/cryostat/core/EventOptionsBuilder.java
- cryostat-core/src/main/java/io/cryostat/core/EventOptionsCustomizer.java
- cryostat-core/src/main/java/io/cryostat/core/net/CryostatFlightRecorderService.java
- cryostat-core/src/main/java/io/cryostat/core/net/JFRConnection.java
- cryostat-core/src/main/java/io/cryostat/core/net/JFRJMXConnection.java
- cryostat-core/src/main/java/io/cryostat/core/net/JmxFlightRecorderService.java
- cryostat-core/src/main/java/io/cryostat/core/reports/InterruptibleReportGenerator.java
- libcryostat/pom.xml
- pom.xml
Related to https://github.com/cryostatio/cryostat/issues/133
Adds an interface method for invoking MBean operations, and a default implementation for doing this over JMX connections that simply wraps around the existing MBeanServerConnection.
> feat(diagnostic): add interface method for invoking MBean operations

- libcryostat/src/main/java/io/cryostat/libcryostat/templates/TemplateType.java
Related to https://github.com/cryostatio/cryostat/issues/548
Adds a third event template type, `PRESET`. These are intended to be pre-loaded `.jfc` files that ship with Cryostat, somewhat akin to Custom event templates, except that Custom templates are explicitly mutable by the end user(s) and can be created or deleted at runtime. Presets ship with Cryostat and are immutable for the user.
> feat(templates): add preset event template type

- cryostat-core/pom.xml
This makes it easier on downstream tooling that needs to do version manipulation.
> chore(pom): use project.version property for libcryostat
