- build.gradle
- src/main/java/com/redhat/rhjmc/containerjfr/core/util/log/Logger.java
- src/test/java/com/redhat/rhjmc/containerjfr/core/util/log/LoggerTest.java
Branch based on top of #5 , last two commits are relevant. Adds basic log4j-like Logger facility.
> Implement basic Logger

- build.gradle
- src/main/java/com/redhat/rhjmc/containerjfr/core/reports/ReportGenerator.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/reports/ReportTransformer.java
- src/test/java/com/redhat/rhjmc/containerjfr/core/reports/ReportGeneratorTest.java
Related to rh-jmc-team/container-jfr#59
> Add automated analysis report generation and transformation

- src/main/java/com/redhat/rhjmc/containerjfr/core/net/JFRConnection.java
Related to rh-jmc-team/container-jfr#59
> Add JFR version check to JFRConnection

- src/main/java/com/redhat/rhjmc/containerjfr/core/FlightRecorderException.java
- src/main/java/com/redhat/rhjmc/containerjfr/core/RecordingOptionsCustomizer.java
- src/test/java/com/redhat/rhjmc/containerjfr/core/RecordingOptionsCustomizerTest.java
Upstreaming a simplified version of the RecordingOptionsCustomizer present in container-jfr
> Implement RecordingOptionsCustomizer

- src/main/java/com/redhat/rhjmc/containerjfr/core/EventOptionsCustomizer.java
- src/test/java/com/redhat/rhjmc/containerjfr/core/EventOptionsCustomizerTest.java
Related to rh-jmc-team/container-jfr#59
> Add EventOptionsCustomizer

- build.gradle
- src/main/java/com/redhat/rhjmc/containerjfr/core/sys/FileSystem.java
This pull request adds FileSystem#exists and FileSystem#pathOf methods. It also increments the patch version number.
Blocks rh-jmc-team/container-jfr#67
> Add exists and pathOf methods to FileSystem

- README.md
- build.gradle
> Update jmc version to latest upstream snapshot

- src/main/java/com/redhat/rhjmc/containerjfr/core/net/JFRConnection.java
These small enhancements to the JFRConnection API will enable better connection management.
> JFRConnection API enhancements

- README.md
> Update README with correct jmc dependency

- src/main/java/com/redhat/rhjmc/containerjfr/core/log/Logger.java
See rh-jmc-team/container-jfr#363
> Add logger functions for performance improvement in container-jfr

- pom.xml
> [v1] Use provided scope for spotbugs-annotation

- src/main/java/com/redhat/rhjmc/containerjfr/core/net/discovery/JvmDiscoveryClient.java
Remove CHANGED discovery event which mirrored JMC API but is not generally applicable. Instead, a pair of LOST/FOUND is now emitted to inform clients of any changes to targets.
> Remove CHANGED discovery event

- src/test/java/com/redhat/rhjmc/containerjfr/core/reports/ReportGeneratorTest.java
> Update text expected whitespace after JSoup update

- README.md
- pom.xml
> [v1] Add AdoptOpenJDK Maven repo

- .github/workflows/ci.yaml
* Create ci.yml
* Change extension from yml to yaml
> [v1] Create ci.yml (#81)

- pom.xml
Bumping version to bring in #88
> Bump version to 1.2.3

- pom.xml
> chore(version): bump project version to 2.3.1

- pom.xml
> build(version): set version to 2.4.0

- pom.xml
> build(version): set version to 2.5.0-SNAPSHOT

- src/main/java/io/cryostat/core/sys/FileSystem.java
Fixes https://github.com/cryostatio/cryostat-core/issues/113
> feat(filesystem): add abstractions for creating (temp) files/dirs

- src/main/java/io/cryostat/core/CryostatCore.java
> fix(report): register rule eval JFR event on init

- src/main/java/io/cryostat/core/templates/LocalStorageTemplateService.java
- src/main/java/io/cryostat/core/templates/MergedTemplateService.java
- src/main/java/io/cryostat/core/templates/MutableTemplateService.java
- src/main/java/io/cryostat/core/templates/TemplateService.java
- src/test/java/io/cryostat/core/templates/LocalStorageTemplateServiceTest.java
Related to cryostatio/cryostat#829
> feat(templates): improve local storage template input and output type signatures

- src/main/java/io/cryostat/core/sys/FileSystem.java
Related https://github.com/cryostatio/cryostat/issues/566
> feat(fs): Set posix file permissions

- src/main/java/io/cryostat/core/reports/InterruptibleReportGenerator.java
- src/test/java/io/cryostat/core/reports/InterruptibleReportGeneratorTest.java
> feat(reports): allow callers to obtain score map of JFR file output

- src/main/java/io/cryostat/core/reports/InterruptibleReportGenerator.java
- src/main/java/io/cryostat/core/util/RuleFilterParser.java
- src/test/java/io/cryostat/core/util/RuleFilterParserTest.java
Fixes part of #148 
Still need to refactor [cryostat] and [cryostat-reports] once my [PR is merged](https://github.com/cryostatio/cryostat-reports/pull/40)
> chore(util): extract RuleFilterParser utility

- pom.xml
> build(version): update version to 2.13.1

- pom.xml
> build(version): restore version to 2.14.0-SNAPSHOT

- .mergify.yml
Related to cryostatio/cryostat#1118
> ci(mergify): update config for latest release branch

- pom.xml
> chore(pom): bump version to 2.14.1

- src/main/java/io/cryostat/core/net/discovery/JvmDiscoveryClient.java
- src/test/java/io/cryostat/core/net/discovery/JvmDiscoveryClientTest.java
Related to https://github.com/cryostatio/cryostat/pull/1327
Added a new EventKind (`MODIFIED`) to represent an updated target jvm.
> feat(discovery): add new eventkind for modified state

- src/main/java/io/cryostat/core/templates/MutableTemplateService.java
> chore(templates): make InvalidEventTemplateException public

- .github/workflows/dependent-issues.yml
> chore(CI): add dependent-issues workflow

- pom.xml
> fix(logging): depend on SLF4J API, not particular provider

- .mergify.yml
- pom.xml
> chore(release): prepare for cryostat 2.4.0 release

- .github/workflows/ci.yaml
> chore(ci): update concurrency for ci.yaml

- pom.xml
> build(deps): downgrade spotbugs

- .github/workflows/cryostat-test.yml
related: https://github.com/cryostatio/cryostat/issues/1796
> chore(ci): add explicit packages: read permission

- .github/workflows/ci.yml
> feat(ci): publish cryostat3.0 images

- pom.xml
See https://github.com/cryostatio/jfr-datasource/pull/273
> build(pom): remove unused repository

- .github/workflows/push-ci.yml
- pom.xml
Related to https://github.com/cryostatio/cryostat-core/issues/92
Related to #362
> ci(publish): bump version to 3.0.0-SNAPSHOT, publish snapshots on push to main

- .github/workflows/maven-central-release.yml
- .github/workflows/push-ci.yml
- README.md
- pom.xml
See https://github.com/cryostatio/cryostat-core/pull/378
See #362
> build(jdk): upgrade minimum JDK to 17

- .github/workflows/push-ci.yml
> ci(secrets): reusable workflow inherits secrets

- pom.xml
> ci(jreleaser): turn off pomchecker

- .github/workflows/maven-publish.yml
> ci(jdk): build with JDK 17

- .github/workflows/maven-central-publish.yml
> ci(maven): add type to reusable workflow parameter

- .github/workflows/push-ci.yml
- release-snapshot.sh
> ci(maven): use script for releasing snapshots

- .mergify.yml
- pom.xml
- **update mergify**
- **chore(release): set version to 4.0.0-SNAPSHOT**
> chore(release): prepare for 3.0.0 release

- cryostat-core/pom.xml
> build(pom): remove snapshot repository

- .github/workflows/ci.yml
- .github/workflows/push-ci.yml
> ci(publish): typo fix

- cryostat-core/LICENSE
- cryostat-core/LICENSE.txt
> ci(core): copy LICENSE file for build

- .github/workflows/ci.yml
- .github/workflows/github-maven-publish.yml
- .github/workflows/maven-central-publish.yml
- .github/workflows/push-ci.yml
- .github/workflows/release.yml
- cryostat-core/pom.xml
- libcryostat/pom.xml
- pom.xml
- **build(toolchain): set up toolchains plugin, configure poms**
- **ci(toolchains): install JDKs 11 and 17**
- **ci(cryostat): build Cryostat with single JDK version only**
See #426
Fixes #425
Test run: https://github.com/andrewazores/cryostat-core/actions/runs/10043497824/job/27756411088
> ci(modules): build modules using maven toolchains

- pom.xml
See https://github.com/cryostatio/cryostat-core/pull/437
> build(deps): bump org.slf4j:slf4j-api from 2.0.12 to 2.0.13

- pom.xml
See https://github.com/cryostatio/cryostat-core/pull/434
> build(deps): org.apache.commons:commons-lang3 from 3.13.0 to 3.14.0

- pom.xml
This reverts commit f2a649765866e9d016acd0412d9141d5b5085071 #436
> build(deps): revert io.smallrye:jandex-maven-plugin from 3.2.2 to 3.1.8

- .github/workflows/ci.yml
Related to https://github.com/cryostatio/cryostat-core/pull/455
> build(deps): bump actions/upload-artifact to v4

- pom.xml
See https://github.com/cryostatio/cryostat-agent/pull/479
> ci(snapshots): remove trailing slash

- cryostat-core/pom.xml
- libcryostat/pom.xml
> ci(snaphots): remove trailing slashes

- .github/workflows/ci.yml
> ci(podman): remove outdated repo for podman package

- libcryostat/src/main/java/io/cryostat/libcryostat/JvmIdentifier.java
Related to https://github.com/cryostatio/cryostat/issues/803
> fix(jvmid): avoid NPE when target does not have expected MBean attribute

- cryostat-core/src/main/java/io/cryostat/core/net/JFRJMXConnection.java
Related to https://github.com/cryostatio/cryostat/pull/859
> chore(exception): public visibility

- .github/workflows/ci.yml
See https://github.com/cryostatio/cryostat-core/pull/552#issuecomment-3032297071
> ci(pr): do not replace -core snapshot in Cryostat build
